[package]
name = "pdetector"
version = "0.1.0"
edition = "2021"


[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
rosu-map = "0.2.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
